groups:
- name: prometheus
  rules:
  - alert: prometheustargetsyncfailure
    labels:
      rackspace_com_coreAccountID: default_coreID
      rackspace_com_overseerID: default_overseerID
      severity: warning
      group_name: default_group_name
      node_name: default_node_name
      pod_name: default_pod_name
    expr: increase(prometheus_target_sync_failed_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[30m])
      > 0
    for: 5m
    annotations:
      description: '{{ printf "%.0f" $value }} targets in Prometheus {{$labels.namespace}}/{{$labels.pod}}
        have failed to sync because invalid configuration was supplied.'
      runbook_url: default_runbook_url
      summary: Prometheus has failed to sync targets.
      dashboard_url: default_dashboard_url
