groups:
- name: prometheus
  rules:
  - alert: prometheuserrorsendingalertstosomealertmanagers
    labels:
      rackspace_com_coreAccountID: default_coreID
      rackspace_com_overseerID: default_overseerID
      severity: warning
      group_name: default_group_name
      node_name: default_node_name
      pod_name: default_pod_name
    expr: "(\n  rate(prometheus_notifications_errors_total{job=\"kube-prometheus-stack-prometheus\"\
      ,namespace=\"prometheus\"}[5m])\n/\n  rate(prometheus_notifications_sent_total{job=\"\
      kube-prometheus-stack-prometheus\",namespace=\"prometheus\"}[5m])\n)\n* 100\n\
      > 1"
    for: 15m
    annotations:
      description: '{{ printf "%.1f" $value }}% of alerts sent by Prometheus {{$labels.namespace}}/{{$labels.pod}}
        to Alertmanager {{$labels.alertmanager}} were affected by errors.'
      runbook_url: default_runbook_url
      summary: More than 1% of alerts sent by Prometheus to a specific Alertmanager
        were affected by errors.
      dashboard_url: default_dashboard_url
