groups:
- name: prometheus
  rules:
  - alert: prometheusscrapesamplelimithit
    labels:
      rackspace_com_coreAccountID: default_coreID
      rackspace_com_overseerID: default_overseerID
      severity: warning
      group_name: default_group_name
      node_name: default_node_name
      pod_name: default_pod_name
    expr: increase(prometheus_target_scrapes_exceeded_sample_limit_total{job="kube-prometheus-stack-prometheus",namespace="prometheus"}[5m])
      > 0
    for: 15m
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has failed {{
        printf "%.0f" $value }} scrapes in the last 5m because some targets exceeded
        the configured sample_limit.
      runbook_url: default_runbook_url
      summary: Prometheus has failed scrapes that have exceeded the configured sample
        limit.
      dashboard_url: default_dashboard_url
