groups:
- name: alertmanager.rules
  rules:
  - alert: alertmanagermembersinconsistent
    labels:
      rackspace_com_coreAccountID: default_coreID
      rackspace_com_overseerID: default_overseerID
      severity: warning
      group_name: default_group_name
      node_name: default_node_name
      pod_name: default_pod_name
    expr: "# Without max_over_time, failed scrapes could create false negatives, see\n\
      # https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0 for details.\n\
      \  max_over_time(alertmanager_cluster_members{job=\"kube-prometheus-stack-alertmanager\"\
      ,container=\"alertmanager\",namespace=\"prometheus\"}[5m])\n< on (namespace,service,cluster)\
      \ group_left\n  count by (namespace,service,cluster) (max_over_time(alertmanager_cluster_members{job=\"\
      kube-prometheus-stack-alertmanager\",container=\"alertmanager\",namespace=\"\
      prometheus\"}[5m]))"
    for: 15m
    annotations:
      description: Alertmanager {{ $labels.namespace }}/{{ $labels.pod}} has only
        found {{ $value }} members of the {{$labels.job}} cluster.
      runbook_url: default_runbook_url
      summary: A member of an Alertmanager cluster has not found all other cluster
        members.
      dashboard_url: default_dashboard_url
