groups:
- name: alertmanager.rules
  rules:
  - alert: alertmanagerclusterfailedtosendalerts
    labels:
      rackspace_com_coreAccountID: default_coreID
      rackspace_com_overseerID: default_overseerID
      severity: warning
      group_name: default_group_name
      node_name: default_node_name
      pod_name: default_pod_name
    expr: "min by (namespace,service, integration) (\n  rate(alertmanager_notifications_failed_total{job=\"\
      kube-prometheus-stack-alertmanager\",container=\"alertmanager\",namespace=\"\
      prometheus\", integration!~`.*`}[15m])\n/\n  ignoring (reason) group_left rate(alertmanager_notifications_total{job=\"\
      kube-prometheus-stack-alertmanager\",container=\"alertmanager\",namespace=\"\
      prometheus\", integration!~`.*`}[15m])\n)\n> 0.01"
    for: 5m
    annotations:
      description: The minimum notification failure rate to {{ $labels.integration
        }} sent from any instance in the {{$labels.job}} cluster is {{ $value | humanizePercentage
        }}.
      runbook_url: default_runbook_url
      summary: All Alertmanager instances in a cluster failed to send notifications
        to a non-critical integration.
      dashboard_url: default_dashboard_url
