groups:
- name: alertmanager.rules
  rules:
  - alert: alertmanagerfailedtosendalerts
    labels:
      rackspace_com_coreAccountID: default_coreID
      rackspace_com_overseerID: default_overseerID
      severity: warning
      group_name: default_group_name
      node_name: default_node_name
      pod_name: default_pod_name
    expr: "(\n  rate(alertmanager_notifications_failed_total{job=\"kube-prometheus-stack-alertmanager\"\
      ,container=\"alertmanager\",namespace=\"prometheus\"}[15m])\n/\n  ignoring (reason)\
      \ group_left rate(alertmanager_notifications_total{job=\"kube-prometheus-stack-alertmanager\"\
      ,container=\"alertmanager\",namespace=\"prometheus\"}[15m])\n)\n> 0.01"
    for: 5m
    annotations:
      description: Alertmanager {{ $labels.namespace }}/{{ $labels.pod}} failed to
        send {{ $value | humanizePercentage }} of notifications to {{ $labels.integration
        }}.
      runbook_url: default_runbook_url
      summary: An Alertmanager instance failed to send notifications.
      dashboard_url: default_dashboard_url
