groups:
- name: kubernetes-apps
  rules:
  - alert: kubedeploymentgenerationmismatch
    labels:
      rackspace_com_coreAccountID: default_coreID
      rackspace_com_overseerID: default_overseerID
      severity: warning
      group_name: default_group_name
      node_name: default_node_name
      pod_name: default_pod_name
    expr: "kube_deployment_status_observed_generation{job=\"kube-state-metrics\",\
      \ namespace=~\".*\"}\n  !=\nkube_deployment_metadata_generation{job=\"kube-state-metrics\"\
      , namespace=~\".*\"}"
    for: 15m
    annotations:
      description: Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment
        }} does not match, this indicates that the Deployment has failed but has not
        been rolled back on cluster {{ $labels.cluster }}.
      runbook_url: default_runbook_url
      summary: Deployment generation mismatch due to possible roll-back
      dashboard_url: default_dashboard_url
