groups:
- name: prometheus-operator
  rules:
  - alert: prometheusoperatorstatusupdateerrors
    labels:
      rackspace_com_coreAccountID: default_coreID
      rackspace_com_overseerID: default_overseerID
      severity: warning
      group_name: default_group_name
      node_name: default_node_name
      pod_name: default_pod_name
    expr: (sum by (cluster,controller,namespace) (rate(prometheus_operator_status_update_errors_total{job="kube-prometheus-stack-operator",namespace="prometheus"}[5m])))
      / (sum by (cluster,controller,namespace) (rate(prometheus_operator_status_update_operations_total{job="kube-prometheus-stack-operator",namespace="prometheus"}[5m])))
      > 0.1
    for: 10m
    annotations:
      description: '{{ $value | humanizePercentage }} of status update operations
        failed for {{ $labels.controller }} controller in {{ $labels.namespace }}
        namespace.'
      runbook_url: default_runbook_url
      summary: Errors while updating objects status.
      dashboard_url: default_dashboard_url
